#!/usr/bin/env bash
# Script to set up a git remote via ssh on a server

set -u

if [[ $# -eq 0 ]] || [[ $# -gt 3 ]]; then
  printf "Usage: %s <user@host:path> [remote-name] [repo-dir]\n" "$(basename "$0")"
  exit 1
fi

REMOTE_URL=$1
if [[ "$REMOTE_URL" != *":"* ]]; then
    printf "Error: Remote URL must be in the format user@host:path\n"
    exit 1
fi
REMOTE_NAME=${2:-origin}

REPO_DIR="${3:-$(pwd)}"

gitc () {
  git -C "$REPO_DIR" "$@"
}

gitc remote | grep "\<$REMOTE_NAME\>" > /dev/null
if [[ $? -eq 0 ]]; then
  printf "Remote %s already exists\n" "$REMOTE_NAME"
  exit 1
fi

# Find git root, init repo if it doesn't exist
GIT_ROOT=$(gitc rev-parse --show-toplevel)
if [[ $? -eq 128 ]]; then
  set -e

  printf "%s was not a git repository, initializing...\n" "$REPO_DIR"
  gitc init
  GIT_ROOT=$(gitc rev-parse --show-toplevel)
  printf "Successfully initialized repository at %s\n" "$REPO_DIR"
fi

set -e

REPO_NAME="$(basename "$GIT_ROOT")".git
REMOTE_URL="$REMOTE_URL/$REPO_NAME"
printf "Creating bare repo at: %s\n" "$REMOTE_URL"
REMOTE_PATH=${REMOTE_URL##*:}
REMOTE_CMD=$(printf 'set -e; mkdir -p %q && git -C %q init --bare' "$REMOTE_PATH" "$REMOTE_PATH")
ssh "${REMOTE_URL%:*}" "$REMOTE_CMD"

gitc remote add "$REMOTE_NAME" "$REMOTE_URL"
gitc push --mirror --set-upstream "$REMOTE_NAME"
