# makeShellInitModule — install a shellinit rc file into share/shellinit/
#
# Optionally also installs a thin profile.d stub so the module is sourced
# by traditional login shells that process /etc/profile.d/.
#
# The stub is a pure sh wrapper that guards on $BASH_VERSION before sourcing
# the rc file, since profile.d is processed by /bin/sh on some systems and
# the rc files use bash-specific syntax.
#
# Arguments:
#   moduleName  — the shellinit module name (filename without .sh)
#                 used in requires= headers and as the install filename:
#                   "api-curl"  → share/shellinit/api-curl.sh
#                   "atlassian" → share/shellinit/atlassian.sh
#   src         — path to the source rc file
#   profileD    — if true, also install a profile.d stub (default: false)
#   meta        — attrset passed through to meta
#
# Usage in a package default.nix:
#
#   { lib, self, makeShellInitModule }:
#   makeShellInitModule {
#     moduleName = "api-curl";
#     src        = self + "/api_curl_helpers_rc.sh";
#     profileD   = true;   # optional — also install etc/profile.d/api-curl.sh
#     meta = with lib; {
#       description = "shellinit module providing api_curl and keepalive";
#       license = licenses.gpl3;
#     };
#   }

{ lib, runCommand, writeText }:

{ moduleName
, src
, profileD ? false
, propagatedBuildInputs ? []
, meta ? {}
}:

let
  # The profile.d stub sources the rc file via its absolute store path.
  # Wrapped in a $BASH_VERSION guard since profile.d is processed by /bin/sh
  # on some systems and the rc files use bash-specific syntax.
  profileDStub = writeText "${moduleName}.sh" ''
    # ${moduleName} — profile.d stub (generated by makeShellInitModule)
    # Sources the shellinit rc file when running under bash.
    [ -n "$BASH_VERSION" ] || return
    # shellcheck shell=bash
    # shellcheck source=/dev/null
    source "@shellinit_rc@"
  '';
in
runCommand "${moduleName}-shellinit-module" { inherit meta propagatedBuildInputs; } (
  ''
    install -Dm644 ${src} $out/share/shellinit/${moduleName}.sh
  ''
  + lib.optionalString profileD ''

    # Write the profile.d stub with the rc store path baked in
    install -dm755 $out/etc/profile.d
    sed "s|@shellinit_rc@|$out/share/shellinit/${moduleName}.sh|g" \
      ${profileDStub} \
      > $out/etc/profile.d/${moduleName}.sh
    chmod 644 $out/etc/profile.d/${moduleName}.sh
  ''
)
